### ISSUE TITLE
Optional Parameters for Build

### ISSUE THREAD

**Issue by michaelstonis** [bitrise-io/xamarin-builder#19]
Would it be possible to add in an additional configurations variable to the `build_commands` method? For example, we need to pass in custom build parameters into xbuild to get our build configured properly from the command line.

For example, when we build a project it looks something like the following:

`xbuild '/Users/User/Development/MyProj.csproj' /t:Clean /t:Build /p:BuildIpa=true /p:Configuration='Release' /p:EnvironmentConfigs='Ad-Hoc' /p:CodesignKey='Test'`

**Comment by aflorenzan** [comment]
This feature can help to solve this [issue](https://github.com/realm/realm-dotnet/issues/656) with Realm powered apps.

**Comment by godrei** [comment]
Hi @michaelstonis and @aflorenzan ,
how would it fit for you, if the [step](https://github.com/bitrise-steplib/steps-xamarin-builder) would be able to append extra arguments to build commands per project types?

The problem is: our shared xamarin builder tool parses the solution and included projects. Based on this informations it creates the required build commands, builds them and collects the generated outputs.

Because of the commands are generated during the step/tool run, there is no way to pre define arguments per commands.

But the next version of the shared build tool will use a callback to notify t's caller before the command run, so at this point we will know for which project (with every parsed information)  was the command generated.

This would allow the step (the caller of the shared builder tool), to append arguments to commands per project type.

To achieve this we would introduce new inputs per project types, like: `ios_build_command_custom_arguments`, `android_build_command_custom_arguments`, ...

This input values would be used like: 

`xbuild "SOLUTION.sln" "/target:Build" "/p:Configuration=CONFIGURATION" "/p:Platform=PLATFORM" $ios_build_command_custom_arguments`

What do you think?

**Comment by michaelstonis** [comment]
This would be fantastic. It would absolutely help solve the issues that we are facing.

**Comment by godrei** [comment]
Hi @michaelstonis, @aflorenzan 

The new xamarin-archive step is available in the steplib. It has inputs to append custom options to build commands.

The blogpost about the new step and migration:
http://blog.bitrise.io/2016/10/18/the-new-xamarin-archive-step.html
